const { AuditLog } = require('../database/models');

const AUDIT_ACTIONS = {
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  EMAIL_CHANGE: 'EMAIL_CHANGE',
  PREFERENCES_UPDATE: 'PREFERENCES_UPDATE',
  ACCOUNT_DELETE: 'ACCOUNT_DELETE',
  ORGANIZATION_UPDATE: 'ORGANIZATION_UPDATE',
  RESEARCHER_PROFILE_UPDATE: 'RESEARCHER_PROFILE_UPDATE',
  ACADEMIC_HISTORY_CREATE: 'ACADEMIC_HISTORY_CREATE',
  ACADEMIC_HISTORY_UPDATE: 'ACADEMIC_HISTORY_UPDATE',
  ACADEMIC_HISTORY_DELETE: 'ACADEMIC_HISTORY_DELETE',
  CERTIFICATION_CREATE: 'CERTIFICATION_CREATE',
  CERTIFICATION_UPDATE: 'CERTIFICATION_UPDATE',
  CERTIFICATION_DELETE: 'CERTIFICATION_DELETE',
  AGREEMENT_CREATED: 'AGREEMENT_CREATED',
  AGREEMENT_UPDATED: 'AGREEMENT_UPDATED',
  AGREEMENT_SUBMITTED_FOR_REVIEW: 'AGREEMENT_SUBMITTED_FOR_REVIEW',
  AGREEMENT_REVIEW_APPROVED: 'AGREEMENT_REVIEW_APPROVED',
  AGREEMENT_CHANGES_REQUESTED: 'AGREEMENT_CHANGES_REQUESTED',
  AGREEMENT_APPROVED_FOR_SIGNATURE: 'AGREEMENT_APPROVED_FOR_SIGNATURE',
  AGREEMENT_PARTY_SIGNED: 'AGREEMENT_PARTY_SIGNED',
  AGREEMENT_EXECUTED: 'AGREEMENT_EXECUTED',
  AGREEMENT_EFFECTIVE: 'AGREEMENT_EFFECTIVE',
  AGREEMENT_ACTIVATED: 'AGREEMENT_ACTIVATED',
  AGREEMENT_COMPLETED: 'AGREEMENT_COMPLETED',
  AGREEMENT_ARCHIVED: 'AGREEMENT_ARCHIVED',
  AGREEMENT_TERMINATED: 'AGREEMENT_TERMINATED',
  AGREEMENT_REMOVAL_REQUESTED: 'AGREEMENT_REMOVAL_REQUESTED',
  AGREEMENT_REMOVAL_APPROVED: 'AGREEMENT_REMOVAL_APPROVED',
  AGREEMENT_REMOVAL_REJECTED: 'AGREEMENT_REMOVAL_REJECTED',
  MILESTONE_REVISION_REQUESTED: 'MILESTONE_REVISION_REQUESTED',
  MILESTONE_REVISION_APPROVED: 'MILESTONE_REVISION_APPROVED',
  MILESTONE_REVISION_REJECTED: 'MILESTONE_REVISION_REJECTED',
  MILESTONE_REQUEST_CREATED: 'MILESTONE_REQUEST_CREATED',
  MILESTONE_REQUEST_APPROVED: 'MILESTONE_REQUEST_APPROVED',
  MILESTONE_REQUEST_REJECTED: 'MILESTONE_REQUEST_REJECTED',
  PROJECT_RESEARCHER_ACCESS_UPDATED: 'PROJECT_RESEARCHER_ACCESS_UPDATED',
  ADMIN_BULK_USER_APPROVED: 'ADMIN_BULK_USER_APPROVED',
  ADMIN_BULK_USER_SUSPENDED: 'ADMIN_BULK_USER_SUSPENDED',
  ADMIN_BULK_USER_UNSUSPENDED: 'ADMIN_BULK_USER_UNSUSPENDED',
  ADMIN_BULK_USER_DELETED: 'ADMIN_BULK_USER_DELETED',
  ADMIN_BULK_PROJECT_STATUS_UPDATED: 'ADMIN_BULK_PROJECT_STATUS_UPDATED',
  ADMIN_BULK_PROJECT_APPROVED: 'ADMIN_BULK_PROJECT_APPROVED',
  ADMIN_BULK_PROJECT_REJECTED: 'ADMIN_BULK_PROJECT_REJECTED',
  ADMIN_BULK_PROJECT_CHANGES_REQUESTED: 'ADMIN_BULK_PROJECT_CHANGES_REQUESTED',
  ADMIN_BULK_PROJECT_DELETED: 'ADMIN_BULK_PROJECT_DELETED',
  ADMIN_BULK_MILESTONE_DELETED: 'ADMIN_BULK_MILESTONE_DELETED',
  ADMIN_BULK_ORGANIZATION_DELETED: 'ADMIN_BULK_ORGANIZATION_DELETED',
  ADMIN_ATTACHMENT_FORCE_DELETED: 'ADMIN_ATTACHMENT_FORCE_DELETED',
  ADMIN_BULK_ATTACHMENT_FORCE_DELETED: 'ADMIN_BULK_ATTACHMENT_FORCE_DELETED',
  ADMIN_BULK_REVIEW_MODERATED: 'ADMIN_BULK_REVIEW_MODERATED',
  ADMIN_UPLOAD_INCIDENT_RESOLVED: 'ADMIN_UPLOAD_INCIDENT_RESOLVED',
  ADMIN_MESSAGE_UPLOAD_ASSET_FORCE_DELETED: 'ADMIN_MESSAGE_UPLOAD_ASSET_FORCE_DELETED',
  UPLOAD_SECURITY_REJECTED: 'UPLOAD_SECURITY_REJECTED',
  UPLOAD_SECURITY_SCAN_FAILED: 'UPLOAD_SECURITY_SCAN_FAILED',
  UPLOAD_SECURITY_USER_SUSPENDED: 'UPLOAD_SECURITY_USER_SUSPENDED'
};

async function logAudit({ actorId, action, entityType, entityId, metadata = {} }) {
  try {
    await AuditLog.create({
      actor_id: actorId || null,
      action,
      entity_type: entityType,
      entity_id: entityId || null,
      metadata,
      timestamp: new Date(),
    });
  } catch (error) {
    if (String(error.message || '').includes('column "metadata"')) {
      try {
        await AuditLog.sequelize.query(
          `INSERT INTO audit_logs (actor_id, action, entity_type, entity_id, timestamp)
           VALUES (:actor_id, :action, :entity_type, :entity_id, :timestamp)`,
          {
            replacements: {
              actor_id: actorId || null,
              action,
              entity_type: entityType,
              entity_id: entityId || null,
              timestamp: new Date(),
            },
          }
        );
        return;
      } catch (fallbackError) {
        console.error('Audit logging fallback failed:', fallbackError.message);
        return;
      }
    }

    console.error('Audit logging failed:', error.message);
  }
}

module.exports = {
  AUDIT_ACTIONS,
  logAudit,
};
